# -*- coding: utf-8 -*-
"""ChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i75wcImLApbJGenVwYJoVtS4dF14H65g
"""

print("\nWelcome to the ChatBot services of ABC Bank!")
print("\nType 'EXIT' at any time to leave the program.")

while True:
  user_input= input("\nInput  : ")
  user_input=user_input.lower()

  if user_input == "exit":
    print("\nThank you...!!!")
    break

  elif user_input in ["hi","hello","hey"]:
    print("\nHello! I am your bank chatbot, how can I help you?")


  elif "name" in user_input:
    print("\nMy name is chatbot...I am here to guide you with digital banking...")


  elif "bank balance" in user_input:
    print("\nHello...Can you share your bank account details with me ?")


  elif "contact infomation" in user_input:
    print("\nYou can contact us via 1779, bankBotVia@mail.com")


  else:
    print("\nEnter a valid input...!")