# -*- coding: utf-8 -*-
"""Dictionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpJQcq6aU-YZz6vIOCzRnALtyIK1W-Fk

Empty dictionaries
"""

dict1 = {}
print(dict1)
print(type(dict1))

dict2 = dict ()
print(dict2)
print(type(dict2))

"""creating dictionaires with values"""

my_dict = {"name":"Alice" , "age":50}
print(my_dict)
print(type(my_dict))

student1 = {"name":"Shane" , "age":40, "city":"London"}
print(student1)
print(student1["name"])
print(student1["age"])
print(student1["city"])

print(f"My name is {student1["name"]}, I am {student1["age"]} years old and I'm from {student1["city"]}.")

"""Accessing values"""

student1 = {"name":"Shane" , "age":40, "city":"London"}
print(student1["city"]) # no key - key error
print(student1.get("city")) # no key - returns none - or default valy=ue

student1 = {"name":"Shane" , "age":40, "city":"London"}
# print(student1["city"]) --> Error
print(student1.get("surname")) # prints None

"""Adding and Updating"""

student1 = {"name":"Shane" , "age":40, "city":"London"}
student1["email"] = "shane@gmail.com" # add
print(student1)

student1 = {"name":"Shane" , "age":40, "city":"London"}
student1["email"] = "12345shane@gmail.com" # update
print(student1)

"""Removing items"""

student1 = {"name":"Shane" , "age":40, "city":"London", "email":"shane@gmail.com"}
print(student1)

student1.pop("email") # Remove by key
print(student1)

del student1["city"] # Delete by key
print(student1)

student1.clear() # Remove all items
print(student1)

student1 = {"name":"Shane" , "age":40, "city":"London", "email":"shane@gmail.com"}
print(student1)
print(len(student1))

"""**.strip() - Usage- cleaning user input or reading data from text files (Removing Spaces)**"""

text = "   hello   "
print(text)
newText = text.strip()
print(newText)