# -*- coding: utf-8 -*-
"""Sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9E4cI42y7z0s2k3WDeUxzJoIQg3O3jY

# ***Sets***

Creating a set
"""

my_set2 = set()
print(my_set2)
print(type(my_set2))

"""Creating a set with values"""

my_set1 = {1,2,3}
print(my_set1)
print(type(my_set1))

number_set = {0,1,2,3,4,4,4,5,5,6,7,-3,0,-10,15}
print(number_set)

"""Adding and removing elements

Adding
"""

my_set = {1,2,3}
print(my_set)
my_set.add(4)
print(my_set)

"""Updating"""

myNewSet = {1,2,3,4,5,6,7,8,}
print(myNewSet)
myNewSet.update([9,10])
print(myNewSet)

"""Removing"""

mySet = {1,2,3,4,5,6,7,8,}
print(mySet)

mySet.remove(2) #remove specific element - error if not found
print(mySet)
mySet.discard(8) #remove specific element - no error if not found
print(mySet)
mySet.pop() #remove one random element
print(mySet)
mySet.clear() #clear all
print(mySet)

"""***Exercise***"""

my_set3 = {101,102,103,104,105,106,107,108}
print(my_set3)

my_set3.add(109)
print(my_set3)

my_set3.update([110,111,112])
print(my_set3)

my_set3.remove(101)
print(my_set3)

my_set3.discard(200)
print(my_set3)

my_set3.pop()
print(my_set3)

my_set3.clear()
print(my_set3)

"""***Set - Core Operators***

**Set operators -** ***union*** ( | )
"""

A = {1,2,3}
B = {4,5,6}

print(A.union(B))
print(B.union(A))

A = {1,2,3}
B = {4,5,6}

print(A | B)
print(B | A)

"""**Set operators -** ***Intersection*** ( & )




"""

A = {1,2,3,4,5,6}
B = {4,5,6,7,8,9}

print(A.intersection(B))
print(B.intersection(A))

A = {1,2,3,4,5,6}
B = {4,5,6,7,8,9}

print(A & B)
print(B & A)

"""**Set operators -** ***Difference*** ( - )







"""

A = {1,2,3}
B = {3,4,5}

print(A.difference(B))
print(B.difference(A))

A = {1,2,3}
B = {3,4,5}

print(A - B)
print(B - A)