{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64436bb3-ba9a-476c-bffa-3de3adadd152",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "\n",
    "window = tk.Tk() \n",
    "window.title(\"Simple Calculator\") \n",
    "window.geometry(\"325x425\") \n",
    "\n",
    "# Clear function \" C \"\n",
    "def click_clear():\n",
    "    display.config(text=\"0\") \n",
    "\n",
    "# Equal function \" = \"\n",
    "def click_equal():\n",
    "    try:\n",
    "        display.config(text=str(eval(display.cget(\"text\"))))\n",
    "    except Exception:\n",
    "        display.config(text=\"Error\")\n",
    "\n",
    "# Number and operator helper function\n",
    "def add_to_screen(character):\n",
    "    current_text = display.cget(\"text\")\n",
    "    if current_text == \"0\" or current_text == \"Error\":\n",
    "        display.config(text=character)\n",
    "    else:\n",
    "        display.config(text=current_text + character)\n",
    "\n",
    "# button functions\n",
    "def click_1(): add_to_screen(\"1\")\n",
    "def click_2(): add_to_screen(\"2\")\n",
    "def click_3(): add_to_screen(\"3\")\n",
    "def click_4(): add_to_screen(\"4\")\n",
    "def click_5(): add_to_screen(\"5\")\n",
    "def click_6(): add_to_screen(\"6\")\n",
    "def click_7(): add_to_screen(\"7\")\n",
    "def click_8(): add_to_screen(\"8\")\n",
    "def click_9(): add_to_screen(\"9\")\n",
    "def click_0(): add_to_screen(\"0\")\n",
    "def click_dot(): add_to_screen(\".\")\n",
    "def click_plus(): add_to_screen(\"+\")\n",
    "def click_multiply(): add_to_screen(\"*\")\n",
    "def click_divide(): add_to_screen(\"/\")\n",
    "\n",
    "# Display screen\n",
    "display = tk.Label(window, text=\"0\", font=(\"Arial\", 26, \"bold\"), anchor=\"e\", bg=\"white\", bd=10, relief=\"sunken\")\n",
    "display.pack(side=\"top\", fill=\"x\", padx=10, pady=15)\n",
    "\n",
    "# Buttons panel\n",
    "button_frame = tk.Frame(window)\n",
    "button_frame.pack(side=\"bottom\", fill=\"both\", expand=True, padx=10, pady=10)\n",
    "\n",
    "# make the buttons stretch and fill up the entire window evenly\n",
    "# === Configure rows manually\n",
    "button_frame.rowconfigure(0, weight=1)\n",
    "button_frame.rowconfigure(1, weight=1)\n",
    "button_frame.rowconfigure(2, weight=1)\n",
    "button_frame.rowconfigure(3, weight=1)\n",
    "\n",
    "# === Configure columns manually\n",
    "button_frame.columnconfigure(0, weight=1)\n",
    "button_frame.columnconfigure(1, weight=1)\n",
    "button_frame.columnconfigure(2, weight=1)\n",
    "button_frame.columnconfigure(3, weight=1)\n",
    "\n",
    "# Row 0 \n",
    "btn1 = tk.Button(button_frame, text=\"1\", font=(\"Arial\", 20, \"bold\"), command=click_1)\n",
    "btn1.grid(row=0, column=0, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn2 = tk.Button(button_frame, text=\"2\", font=(\"Arial\", 20, \"bold\"), command=click_2)\n",
    "btn2.grid(row=0, column=1, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn3 = tk.Button(button_frame, text=\"3\", font=(\"Arial\", 20, \"bold\"), command=click_3)\n",
    "btn3.grid(row=0, column=2, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn4 = tk.Button(button_frame, text=\"+\", font=(\"Arial\", 20, \"bold\"), command=click_plus)\n",
    "btn4.grid(row=0, column=3, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "# Row 1 \n",
    "btn5 = tk.Button(button_frame, text=\"4\", font=(\"Arial\", 20, \"bold\"), command=click_4)\n",
    "btn5.grid(row=1, column=0, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn6 = tk.Button(button_frame, text=\"5\", font=(\"Arial\", 20, \"bold\"), command=click_5)\n",
    "btn6.grid(row=1, column=1, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn7 = tk.Button(button_frame, text=\"6\", font=(\"Arial\", 20, \"bold\"), command=click_6)\n",
    "btn7.grid(row=1, column=2, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn8 = tk.Button(button_frame, text=\".\", font=(\"Arial\", 20, \"bold\"), command=click_dot)\n",
    "btn8.grid(row=1, column=3, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "# Row 2 \n",
    "btn9 = tk.Button(button_frame, text=\"7\", font=(\"Arial\", 20, \"bold\"), command=click_7)\n",
    "btn9.grid(row=2, column=0, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn10 = tk.Button(button_frame, text=\"8\", font=(\"Arial\", 20, \"bold\"), command=click_8)\n",
    "btn10.grid(row=2, column=1, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn11 = tk.Button(button_frame, text=\"9\", font=(\"Arial\", 20, \"bold\"), command=click_9)\n",
    "btn11.grid(row=2, column=2, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn12 = tk.Button(button_frame, text=\"X\", font=(\"Arial\", 20, \"bold\"), command=click_multiply) \n",
    "btn12.grid(row=2, column=3, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "# Row 3 \n",
    "btn13 = tk.Button(button_frame, text=\"=\", font=(\"Arial\", 20, \"bold\"), command=click_equal)\n",
    "btn13.grid(row=3, column=0, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn14 = tk.Button(button_frame, text=\"0\", font=(\"Arial\", 20, \"bold\"), command=click_0)\n",
    "btn14.grid(row=3, column=1, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn15 = tk.Button(button_frame, text=\"C\", font=(\"Arial\", 20, \"bold\"), command=click_clear)\n",
    "btn15.grid(row=3, column=2, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "btn16 = tk.Button(button_frame, text=\"/\", font=(\"Arial\", 20, \"bold\"), command=click_divide)\n",
    "btn16.grid(row=3, column=3, sticky=\"nsew\", padx=2, pady=2)\n",
    "\n",
    "window.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cf099ce6-59ac-448b-86fa-9177433e5280",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
