# -*- coding: utf-8 -*-
"""Errors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13J1pDtZpQvzM8UP8eOEAl9gsawYgAw-r

# Syntax Errors
"""

x=15
if x>10
  print("Hello")

x=15
if x>10:
  print("Hello")

"""# systax errors - incorrect indentation"""

for i in range(5):
print(i)

for i in range(5):
  print(i)

"""Systax errors - missspelled python keywords"""

deff calculate():
  pass

def calculate():
  pass

"""# unmatched or brocken string"""

print("Hello)

print("Hello")

"""missing parantheiss"""

print "Hi"

print("Hi")

"""# Runtime error

name error
"""

number = 10
print(num)

number =10
print(number)

"""index errors"""

num_list = [1,2,3]
print(num_list[10]) # 10 is out of range

num_list = [1,2,3]
print(num_list[2]) # only 0,1,2 can use without error within the range

"""type errors"""

str_name = 'John' + 12
print(str_name)

str_name = 23 + 12
print(str_name)

str_name = 'John' + ' Buttler'
print(str_name)

"""value error"""

print(int("hello"))

i=10.00
print(int(i))
print(type(i))

"""import error / module not found error"""

import Math #incorrect module name

import math #correct module name - math in lower case

import pandas

import datetime

import numpy # numerical python

import matplotlib

"""key error"""

data = {"name":"Alex"}
data[age]

data = {"name":"Alex"}
data["name"]

"""Attribute error"""

x =10
x.append(5)

x = [10]
x.append(5)
print(x)

"""Zero devision error"""

10/1

10/2.55

10/0

"""IOError / OSError # permissions/device errors"""

f = open("my_file.txt","r")

# uploaded the text file-Open the file directly by its name now that it is uploaded
with open("test.txt", "r") as f:
    print(f.readline().strip())