# -*- coding: utf-8 -*-
"""Exception_handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVlKMUcF0ckIKfCwzVdm5jzUB7mxRQ4V
"""

print(x)

"""can have one or more except statments in a try - except block"""

try:
  print(x)
except:
  print("An Error Occured") # any error dont crash the prgm and print this

x=10
try:
  print(x)
except:
  print("An Error Occured") # no error so print the actual result

x=10/0

try:
  x=10/0
except:
  print("You cant devide by zero")

num = int(input("Enter a number : "))
print("Valid number :",num)

num = int(input("Enter a number : "))
print("Valid number :",num)

try:
  num = int(input("Enter a number : "))
  print("Valid number :",num)
except:
  print("Error : Not a valid number")

try:
  num = int(input("Enter a number : "))
  print("Valid number :",num)
except:
  print("Error : Not a valid number")

try:
  num = int(input("Enter a number : "))
except ValueError:
  print("Invalid number!")
else:
  print("Success! You entered : ",num)
finally:
  print("This always runs(cleanup,logging,etc.).")

try:
  num = int(input("Enter a number : "))
except ValueError:
  print("Invalid number!")
else:
  print("Success! You entered : ",num)
finally:
  print("This always runs(cleanup,logging,etc.).")

try:
  print(value)
except NameError as e:
  print("Here I can insert customized message",e)

"""Logical errors - due to mustakes done by the programmer

EX : 1
"""

length = 5
width = 10
area = length + width # wrong mathematical operator - not + should be *
print(area)

length = 5
width = 10
area = length * width # correct
print(area)

"""EX : 2"""

a = 12+3*4 # we need output as 60 but gives 24
print(a)

a = (12+3) * 4
print(a)

try:
  value = int(input("Enter a value : "))
  print(value/value)
except ValueError:
  print("Bad Input...")
except ZeroDivisionError:
  print("Cannot divide by zero")

try:
  value = int(input("Enter a value : "))
  print(value/value)
except ValueError:
  print("Bad Input...")
except ZeroDivisionError:
  print("Cannot divide by zero")

try:
  value = int(input("Enter a value : "))
  print(value/value)
except ValueError:
  print("Bad Input...")
except ZeroDivisionError:
  print("Cannot divide by zero")

"""Exercises"""

value = input ("Enter a value : ")
print(10/value)

try:
  print(int("10")+5)
except ValueError:
  print("Error!")

try:
  val = int("xyz")
except ValueError:
  print("Invalid")
finally:
  print()

"""Catch multipe exceptions"""

try:
  val = int("xyz")
except (ValueError,TypeError):
  print("Invalid")
finally:
  print()

try:
  d = {"a:":1}
  print(d["b"])
except KeyError:
  print("Missing key")
else:
  print("No Error")

answer = input("Enter the marks : ")
try:
  answer=int(answer)
  if not(answer>=0 and answer<=100):
    print("Outside the range! Marks must be between 0 to 100")
  else:
    print("Valid marks entered!")
except ValueError:
  print("Invalid input! Please enter a number !")

answer = input("Enter the marks : ")
try:
  answer=int(answer)
  if not(answer>=0 and answer<=100):
    print("Outside the range! Marks must be between 0 to 100")
  else:
    print("Valid marks entered!")
except ValueError:
  print("Invalid input! Please enter a number !")

answer = input("Enter the marks : ")
try:
  answer=int(answer)
  if not(answer>=0 and answer<=100):
    print("Outside the range! Marks must be between 0 to 100")
  else:
    print("Valid marks entered!")
except ValueError:
  print("Invalid input! Please enter a number !")

answer = input("Enter the marks : ")
try:
  answer=int(answer)
  if not(answer>=0 and answer<=100):
    print("Outside the range! Marks must be between 0 to 100")
  else:
    print("Valid marks entered!")
except ValueError:
  print("Invalid input! Please enter a number !")