# -*- coding: utf-8 -*-
"""ListExercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYKsNJjl5P_GDpolBbSQ87IvDV6UX1Ki
"""

numbers = [5,10,15,20]

numbers = [5,10,15,20]
print(numbers[1])

numbers = [5,10,15,20]
print(numbers[-1])

nums = [2,4,6,8,10]
print(nums[1:4])

pets = ["Dog","Fish","Bird"]
print(pets)

pets[0]="Cat"
print(pets)

fruits = ["apple","mango","banana"]
fruits.append("orange")
print(fruits)

fruits = ["apple","mango","banana"]
fruits.append("orange")
fruits[2]="papaya"
print(fruits)

vehicles = ["bus","car","van"]
vehicles.remove("car")
print(vehicles)