# -*- coding: utf-8 -*-
"""ListPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_xv5s1e4w5DZ-SBHqJSU6gEmYo9nFgQ

Testing Google Colab
"""

print("Hello World!")

number = 22
print(number)

number1 = 20
number2 = 25
print(number1)
print(number2)

"""List and Tuple in Python"""

num1 = (10)
num2 = (10,)
num3 = [10]
num4 = {10}

print(type(num1))
print(type(num2))
print(type(num3))
print(type(num4))

list = []

print(list)
print(type(list))

number = 20,25
print(number)
print(type(number))

"""### ***List***

List are mutable (can be changed)
"""

list_01 = []

print(list_01)
print(type(list_01))

list_02 = list()

print(list_02)
print(type(list_02))

mylist_01 = [10,20,30,40,50]
mylist_02 = list((10,20,30,40,50))

print(mylist_01)
print(type(mylist_01))

print(mylist_02)
print(type(mylist_02))

"""Allow duplicates"""

fruits = ["apple","banana","apple","mango","banana"]
print(fruits)

"""Append - add a signle element to the end of the list"""

numbers = [5,10,15,20,25]
print(numbers)

numbers.append(30)
print(numbers)

"""Replace with Indexing"""

fruits = ["apple","banana","apple","mango","banana"]
print(fruits)

fruits[2] = "orange"
fruits[4] = "grapes"
print(fruits)

myFavFruits = ["Cherry","Berry","Pears"]
print(myFavFruits[0])
print(myFavFruits[1])
print(myFavFruits[2])

"""Adding items by insert - specific position"""

myFavFruits = ["Cherry","Berry","Pears"]
print(myFavFruits)

myFavFruits.insert(2,"Mandarine")
myFavFruits.insert(3,"Strawberry")
print(myFavFruits)

"""Removing items"""

fruits = ["apple","banana","apple","mango","banana"]
print(fruits)

fruits.remove("apple")
print(fruits) # remove item name

fruits.pop()
print(fruits) # remove last element

fruits.pop(0)
print(fruits) # remove by indexing

fruits.clear()
print(fruits) # remove all items

my_list = [20,"john",34,False,"Anne"]

print(my_list[0]) # first element
print(my_list[:3]) # first 3 elements
print(my_list[::-1]) # reverse list
print(my_list[:]) # full copy
print(my_list[2:5]) # slice from 2 to 5
print(my_list[2:]) # slice from 2 to end
print(my_list[2:5:3]) # slice with step - between  2 to 5 indexes get 3 rd index item

"""Nested Lists"""

my_list = [20, "John" , [5,10,15,20] ]
print(my_list)

print(my_list[2]) # [5,10,15,20]
print(my_list[2][0]) # 5
print(my_list[2][1]) # 10
print(my_list[2][2]) # 15
print(my_list[2][3]) # 20

# Insert to nested lists
my_list[2].insert(4,25)
print(my_list[2])

"""length - Sorting - reverse"""

numbers = [200,5,300,10,15,1000,20,25,100,30,500,35,700,40,900,45,50]
print(len(numbers)) # length of the list

numbers.sort()  # sorted
print(numbers)

numbers.reverse() #  reversed
print(numbers)

"""Index of the element"""

num = [5,10,15,20]
print(num)
print(num.index(10))

"""Number of times"""

num = [5,10,15,20,5,5,10]
print(num)
print(num.count(5))
print(num.count(10))

print([1, 2] + [3, 4])

print((1, 2) + (3, 4))

num1 = [1,2]
num2 = [3,4]
print(num1+num2)