# -*- coding: utf-8 -*-
"""TuplePython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pSn_m3bolRsPV1zCYPTnZW_6TEUqYzQ

# **Tuple**

Tuple are immutable - No append, remove, pop - to get fixed data we can use - Id passport NO - Tuples are faster than lists for iteration
"""

my_tuple = ("user_123", 45, False, 99.9)

tuple1 = () #empty
print(tuple1)
print(type(tuple1))

tuple2 = tuple() #empty
print(tuple2)
print(type(tuple2))

tuple1 = (10,20,30,40,50)
tuple2 = tuple((15,20,25,30,35,40))

print(tuple1)
print(tuple2)

"""Tuple supports indexing"""

my_tuple = (10,20,30,40,50)
print(my_tuple[0])
print(my_tuple[1])

list = (10,20,30,40,50)
print(type(list))

"""List to tuple"""

mylist = [10,20,30,40,50]
print(mylist)
print(type(mylist))

mytuple = tuple(mylist)
print(mytuple)
print(type(mytuple))

"""Count (x)"""

my_tuple = (1,1,3,2,4,5)
print(my_tuple.count(1))

"""index(x)"""

my_tuple = (1,1,3,2,4,5)
print(my_tuple.index(5))